### ISSUE TITLE
Separate out delegation revoking methods from setters?

### ISSUE THREAD

**Issue by jakerockland** [0xfoobar/token-delegation#12]
Following up from https://github.com/0xfoobar/nft-delegation/pull/11, most specifically https://github.com/0xfoobar/nft-delegation/pull/11#issuecomment-1215142208, I think it is probably clearer for consuming clients of the registry to have separate setter methods for delegating permissions and for revoking delegations, rather than combining this functionality into the setters.

WDYT @0xfoobar @0xRusowsky @ryley-o?

**Comment by ryley-o** [comment]
yes, I think that makes a lot of sense. Since we are now using enumerable maps for delegations, I think explicitly removing the delegate key would cleanly fit in a revoke function as well. We can also add `revokeAll` method(s) that revoke all delegations if we remove keys.

**Comment by 0xRusowsky** [comment]
I think it can make sense to add explicit functionalities. Nevertheless, I don't dislike the current minimalistic setup, since, with good explainers of the parameters, it shouldn't be an issue.

Overall I don't have a strong opinion on either side (both of them have benefits). So I would wait to see what @0xfoobar thinks of this since he is the repo owner.

**Comment by 0xRusowsky** [comment]
Currently working to implement this on top of the expiration logic since I had the green light from foobar.

`revokeAll` is already implemented with `revokeDelegate`  see #13

In the new implementation I get rid of expiration = 0 as an input value and add `revokeForContract` and `revokeForToken` as the required methods to revoke previously existing delegations.

**Comment by 0xRusowsky** [comment]
Can someone review #17 and see if any further development is needed regarding revokings?
