### ISSUE TITLE
What is the intended use-case for `role`?

### ISSUE THREAD

**Issue by jakerockland** [0xfoobar/token-delegation#8]
Reading over https://github.com/0xfoobar/nft-delegation/blob/main/src/DelegationRegistry.sol, my impression is that `role` is added for the _potential_ for consuming clients of this standard/registry to have custom handling of more nuanced permissions than just the `All`/`Collection`/`Token` divisions of delegated ACLs. 

Is my intuition here around the purpose of `role` correct?

If so, I'm concerned that by adding this generalized set of extra bytes to the standard, it creates the opportunity for different registry clients to use this differently, creating the opportunity for standard divergence, risks of exploits due to unintentional `role` code collisions, etc., and would advocate that if we do have any sort of `role` in this standard, there probably needs to be a `role` registry of sorts that maintains a list of reserved valid roles, which itself is managed by some form of governance...

This feels like a lot of unnecessary complexity to me personally, so my outlook would be that we can just drop the `role` concept altogether, but I'm probably missing some context here @0xfoobar ?

cc @ryley-o

**Comment by ryley-o** [comment]
++ unless there is a defined standard to address specific use cases for how `role` should be used, I am hesitant to want to use it due to the potential collision and associated exploits. Collisions could either be inadvertent (two projects accidentally decide to use same role), or malicious (e.g. project asks user delegate for a role that is also used for something else unexpected).

More context would be awesome 😄

**Comment by 0xfoobar** [comment]
The idea here was separate functionality (claims, events, governance, etc) could be identified with a specific bytes32 role (think keccak256("airdrop"), keccak256("eventTicket")) which enables future compatibility and registry usecase expansion without forcing migration to a new contract.

I agree the bytes32 parameter is clunky and adds additional social layer dependencies for understanding what's going on and how to avoid conflicts. By removing it we hardcode this delegation standard for NFTs and NFTs only. That said, not convinced the additional complexity is warranted. Thoughts?

**Comment by jakerockland** [comment]
That use case generally makes sense, but I think given the necessary social layer dependencies, I would advocate that in this route we do need some sort of role registry + social consensus/governance layer for maintaining said registry to avoid collisions.

> By removing it we hardcode this delegation standard for NFTs and NFTs only. That said, not convinced the additional complexity is warranted. Thoughts?

Is this fully the case or isn't the way that delegation is used still up to client applications and how they integrate with the delegation registry? E.g. a client application could respect the registry to allow for a delegated NFT to be used to claim an ERC20 airdrop. 

I may be misunderstanding your point here, but my gut reaction would be that the complexity isn't warranted here with `role` alone unless we go deep and go full role-registry-with-governance (which I'm definitely not philosophically opposed to, just not sure if there is client buy-in to a degree that would warrant it).

**Comment by arkaydeus** [comment]
All very valid points. Just kicking the tyres here:

- If complexity is the enemy because it reduces security, but lack of flexibility prohibits a large portion of intended use cases, is the risk not that people go elsewhere? Elsewhere being a greater risk?

- Are you significantly more likely to be tricked in terms of a 'role' than being tricked in terms of signing a registry tx irrespective of if role is involved? Most people don't read the data on the txs they sign. How much additional risk is this vs the utility it provides and the dangers of going 'elsewere to do it'

- If the ID were a string (using registry) and the string contained something clearly identifiable, how easy would it be to trick a user into delegating. e.g. if the string was "application123 / useCase 4", would you sign it from a completely random, unrelated website? (possibly yes if the above point is considered but in that scenario, no additional risk, just risk inherent generally as people aren't checking tx data anyway). Does it add higher risk than delegation alone? Not really.

I guess the real question is - where does risk come from? Is the risk that you delegate the wrong application (role) or that you delegate at all? Is the risk that you're using a fragmented delegation patchwork, rather than a single immutable primitive that everyone can trust. If that cannot service most need, it will be ignored for something more usable.

Is the mental model (flattening removing the issue) the attack vector here? Is adding 'application / use case / role' necessarily taking this from safe too risky?

Feels like the real issue is that you click on a button on a website and metamask doesn't tell you anything. Trust is either complete in terms of the smartcontract you're interacting with or not. There's big value in only having to trust that one smartcontract so a high need for it to work in nearly all circumstances.

Though more expensive in terms of gas, using a string with a registry of roles, appears to prevent collisions without adding significant risk.

Roles may not be used most of the time, but not having them could push people to other solutions.

**Comment by 0xfoobar** [comment]
Appreciate the thoughts @arkaydeus! The larger risk feels like adoption fragmentation due to complexity rather than extension use cases. Given the coordination roles would require at the social layer, feels best to leave this out and have a simpler end-user UX.
